FROM node:18.19.1-alpine3.19

# Installs latest Chromium (100) package.
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app

RUN apk add --no-cache curl
RUN npm install -g pnpm@8

COPY package.json tsconfig.base.json tsconfig.json ./
RUN pnpm install

COPY /src ./src

CMD ["npx", "tsx", "watch", "src/devLambdaRunner.ts"]
