FROM node:18.19.1-alpine3.19

# Changing WORKDIR value will also change the paths used in S3.
WORKDIR /app

RUN apk add --no-cache curl
RUN npm install -g pnpm@8

COPY package.json tsconfig.base.json tsconfig.json ./
RUN pnpm install

COPY /src ./src

CMD ["npx", "tsx", "watch", "src/devLambdaRunner.ts"]
