---
version: "3.8"

services:
  app:
    container_name: tiugo-monitoring
    build:
      context: ../
      dockerfile: ./docker/checks-runner/Dockerfile.dev
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src

  grafana:
    build:
      context: ../
      dockerfile: ./docker/grafana/Dockerfile
    depends_on:
      - prometheus
    env_file:
      - ../.env
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    ports:
      - "3000:3000"

  prometheus:
    build:
      context: ../
      dockerfile: ./docker/prometheus/Dockerfile
      args:
        PUSHGATEWAY_URL: "pushgateway:9091"
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus/data",
        "--storage.tsdb.retention.time=60d",
        "--web.config.file=/etc/prometheus/webconfig.yml",
        "--web.enable-admin-api"
      ]
    env_file:
      - ../.env
    ports:
      - 9090:9090

  pushgateway:
    build:
      context: ../
      dockerfile: ./docker/pushgateway/Dockerfile
    env_file:
      - ../.env
    command:
      [ "--web.config.file=/etc/pushgateway/webconfig.yml" ]
    ports:
      - 9091:9091
