---
version: "3.8"

services:
  app:
    container_name: cksource-monitoring
    build: 
      context: ../
      dockerfile: ./docker/app/Dockerfile.dev
    volumes:
      - ../src:/app/src

  grafana:
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=cks
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_AUTH_ANONYMOUS_ENABLED=true
    hostname: grafana
    build:
      context: ../
      dockerfile: ./docker/grafana/Dockerfile
    ports:
      - "3000:3000"
    logging:
      driver: "none"

  prometheus:
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus/data",
        "--storage.tsdb.retention.time=60d"
      ]
    hostname: prometheus
    build:
      context: ../
      dockerfile: ./docker/prometheus/Dockerfile
    logging:
      driver: "none"

  pushgateway:
    hostname: pushgateway
    image: prom/pushgateway:v1.6.2
    logging:
      driver: "none"
