---
version: "3.8"

services:
  app:
    container_name: cksource-monitoring
    build: 
      context: ../
      dockerfile: ./docker/app/Dockerfile.dev
    volumes:
      - ../src:/app/src

  grafana:
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=cks
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_AUTH_ANONYMOUS_ENABLED=true
    build:
      context: ../
      dockerfile: ./docker/grafana/Dockerfile.dev
    ports:
      - "3000:3000"
    logging:
      driver: "none"

  prometheus:
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus/data",
        "--storage.tsdb.retention.time=60d"
      ]
    build:
      context: ../
      dockerfile: ./docker/prometheus/Dockerfile.dev
    ports:
      - 9090:9090
    logging:
      driver: "none"

  pushgateway:
    image: prom/pushgateway:v1.7.0
    ports:
      - 9091:9091
    logging:
      driver: "none"
