---
version: "3.8"

services:
  app:
    container_name: cksource-monitoring
    build: 
      context: ../
      dockerfile: ./docker/tests-runner/Dockerfile.dev
    volumes:
      - ../src:/app/src

  grafana:
    depends_on:
      - prometheus
    env_file:
      - ../.env
    environment:
      - GF_SECURITY_ADMIN_USER=cks
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - PUSHGATEWAY_URL=http://pushgateway:9091
      # - PUSHGATEWAY_URL=https://monitoring-pushgateway.internal.cke-cs-dev.com
    build:
      context: ../
      dockerfile: ./docker/grafana/Dockerfile.dev
    ports:
      - "3000:3000"

  prometheus:
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus/data",
        "--storage.tsdb.retention.time=60d"
      ]
    build:
      context: ../
      dockerfile: ./docker/prometheus/Dockerfile.dev
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway:v1.7.0
    ports:
      - 9091:9091
