apiVersion: 1

contactPoints:
  - orgId: 1
    name: "CKSource Slack"
    receivers:
    - uid: "e5282c6b-1275-4a22-9cbb-cf44cb469259"
      type: "slack"
      settings:
        mentionChannel: "channel"
        text: "{{ range .Alerts }}\n*Description:* {{ .Annotations.description }}{{ if gt (len .GeneratorURL) 0 }}\n<{{ .GeneratorURL }}|Source> {{ end }}{{ if gt (len .SilenceURL) 0 }} <{{ .SilenceURL }}|Silence> {{ end }}{{ end }}"
        title: "[ {{ .Status | toUpper }} ] {{ .CommonLabels.alertname }}"
        url: $SLACK_WEBHOOK_URL
        username: "CKSource Monitoring"
      disableResolveMessage: false

policies:
  - receiver: "CKSource Slack"
    group_by: ["alertname"]
    group_wait: "30s"
    group_interval: "5m"
    repeat_interval: "15m"
