---
version: "3.8"

services:

  prometheus:
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus/data",
        "--storage.tsdb.retention.time=60d"
      ]
    hostname: prometheus
    image: prom/prometheus:v2.47.1
    networks:
      - cksource-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    logging:
      driver: "json-file" # todo: change to none

  pushgateway:
    hostname: pushgateway
    image: prom/pushgateway:v1.6.2
    networks:
      - cksource-monitoring
    ports:
      - "9091:9091"
    logging:
      driver: "json-file" # todo: change to none

  grafana:
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    hostname: grafana
    image: grafana/grafana:10.1.2
    networks:
      - cksource-monitoring
    ports:
      - "3000:3000"
    logging:
      driver: "json-file" # todo: change to none

networks:
  cksource-monitoring:
    driver: bridge
