apiVersion: 1
datasources:
  - name: Prometheus
    uid: d63db6cb-7f33-4769-b4b4-3b4a44f67e84
    type: prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus:9090

    basicAuth: true
    basicAuthUser: cks
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
    secureJsonData:
      basicAuthPassword: $BASIC_AUTH_PASSWORD
    version: 1
    readOnly: false