{
 "title": "ButterCMS dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "ButterCMS Websites", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ButterCMS Websites Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(product_name, test_name) (increase(monitoring_test_fails_counter{status_code!~\"1\", organization=\"ButterCMS\", product_group=\"websites\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "ButterCMS Websites Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(test_name, product_name) (rate(monitoring_test_histogram_sum{status_code!~\"1\", organization=\"ButterCMS\", product_group=\"websites\"}[1m])) / sum by(test_name, product_name) (rate(monitoring_test_histogram_count{status_code!~\"1\", organization=\"ButterCMS\", product_group=\"websites\"}[1m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  { "title": "ButterCMS APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ButterCMS APIs Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(product_name, test_name) (increase(monitoring_test_fails_counter{status_code!~\"1\", organization=\"ButterCMS\", product_group=\"apis\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "ButterCMS APIs Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(test_name, product_name) (rate(monitoring_test_histogram_sum{status_code!~\"1\", organization=\"ButterCMS\", product_group=\"apis\"}[1m])) / sum by(test_name, product_name) (rate(monitoring_test_histogram_count{status_code!~\"1\", organization=\"ButterCMS\", product_group=\"apis\"}[1m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  }
 ]
}