{
 "title": "ButterCMS monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ButterCMS Websites", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ButterCMS Websites Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(product_name, check_name) (increase(monitoring_check_fails_count{check_name=\"ping\", organization=\"ButterCMS\", product_group=\"websites\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "ButterCMS Websites Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(check_name, product_name) (rate(monitoring_check_histogram_sum{check_name=\"ping\", status=\"success\", organization=\"ButterCMS\", product_group=\"websites\"}[2m])) / sum by(check_name, product_name) (rate(monitoring_check_histogram_count{check_name=\"ping\", status=\"success\", organization=\"ButterCMS\", product_group=\"websites\"}[2m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  { "title": "ButterCMS APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ButterCMS APIs Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(product_name, check_name) (increase(monitoring_check_fails_count{check_name=\"ping\", organization=\"ButterCMS\", product_group=\"apis\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "ButterCMS APIs Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(check_name, product_name) (rate(monitoring_check_histogram_sum{check_name=\"ping\", status=\"success\", organization=\"ButterCMS\", product_group=\"apis\"}[2m])) / sum by(check_name, product_name) (rate(monitoring_check_histogram_count{check_name=\"ping\", status=\"success\", organization=\"ButterCMS\", product_group=\"apis\"}[2m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "ButterCMS APIs Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(product_name, check_name) (increase(monitoring_check_fails_count{organization=\"ButterCMS\", product_group=\"apis\", check_name=~\"buttercms_.*\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "ButterCMS APIs Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(check_name, product_name) (rate(monitoring_check_histogram_sum{check_name=\"ping\", status=\"success\", organization=\"ButterCMS\", product_group=\"apis\"}[2m])) / sum by(check_name, product_name) (rate(monitoring_check_histogram_count{check_name=\"ping\", status=\"success\", organization=\"ButterCMS\", product_group=\"apis\"}[2m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  }
 ]
}