{
 "title": "ButterCMS - Certificates and domains",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "ButterCMS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "monitoring_expiration_test_gauge{test_name=\"certificate_expiration\", organization=\"ButterCMS\"}",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "monitoring_expiration_test_gauge{test_name=\"domain_expiration\", organization=\"ButterCMS\"}",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "Internal - tests status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificate tests - fails in last 72h",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "increase(monitoring_test_fails_counter{test_name=\"certificate_expiration\", organization=\"ButterCMS\"}[72h])",
       "legendFormat": "{{product_name}}"
      }
     ]
    },
    {
     "title": "Domain tests - fails in last 72h",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "increase(monitoring_test_fails_counter{test_name=\"domain_expiration\", organization=\"ButterCMS\"}[72h])",
       "legendFormat": "{{product_name}}"
      }
     ]
    }
   ]
  }
 ]
}