{
 "title": "CKSource Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ckeditor.com Website", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ckeditor.com Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(product_name, check_name) (increase(monitoring_check_fails_count{check_name=\"ping\", product_group=\"ckeditorWebsite\", organization=\"CKSource\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "ckeditor.com Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(check_name, product_name) (rate(monitoring_check_histogram_sum{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"ckeditorWebsite\"}[2m])) / sum by(check_name, product_name) (rate(monitoring_check_histogram_count{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"ckeditorWebsite\"}[2m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  { "title": "CKSource CDNs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CKSource CDNs Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(product_name, check_name) (increase(monitoring_check_fails_count{check_name=\"ping\", product_group=\"CDNs\", organization=\"CKSource\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "CKSource CDNs Response Times",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(check_name, product_name) (rate(monitoring_check_histogram_sum{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"CDNs\"}[2m])) / sum by(check_name, product_name) (rate(monitoring_check_histogram_count{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"CDNs\"}[2m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  { "title": "CKSource Websites", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CKSource Websites Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(product_name, check_name) (increase(monitoring_check_fails_count{check_name=\"ping\", product_group=\"websites\", organization=\"CKSource\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "CKSource Websites Response Times",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(check_name, product_name) (rate(monitoring_check_histogram_sum{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"websites\"}[2m])) / sum by(check_name, product_name) (rate(monitoring_check_histogram_count{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"websites\"}[2m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  { "title": "CKSource Internal Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CKSource Internal Tools Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(product_name, check_name) (increase(monitoring_check_fails_count{check_name=\"ping\", product_group=\"internalTools\", organization=\"CKSource\"}[60s]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "CKSource Internal Tools Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(check_name, product_name) (rate(monitoring_check_histogram_sum{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"internalTools\"}[2m])) / sum by(check_name, product_name) (rate(monitoring_check_histogram_count{check_name=\"ping\", status=\"success\", organization=\"CKSource\", product_group=\"internalTools\"}[2m]))",
     "legendFormat": "{{product_name}}"
    }
   ]
  }
 ]
}