{
 "title": "Tiugo - Certificates and domains",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Tiugo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "monitoring_expiration_check_gauge{check_name=\"certificate_expiration\", organization=\"Tiugo\"}",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "monitoring_expiration_check_gauge{check_name=\"domain_expiration\", organization=\"Tiugo\"}",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "Internal - checks status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificate checks - fails in last 72h",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "increase(monitoring_check_fails_counter{check_name=\"certificate_expiration\", organization=\"Tiugo\"}[72h])",
       "legendFormat": "{{product_name}}"
      }
     ]
    },
    {
     "title": "Domain checks - fails in last 72h",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "increase(monitoring_check_fails_counter{check_name=\"domain_expiration\", organization=\"Tiugo\"}[72h])",
       "legendFormat": "{{product_name}}"
      }
     ]
    }
   ]
  }
 ]
}